import { CategoryType } from '@atsumedia/data';

export type ArticleCsvItem = {
	id: string;
	title_path: string;
	series_path: string;
	episode_path: string;
	program_title: string;
	primary_program: string;
	title_meta: string;
	description_meta: string;
	network_1: string;
	season?: string;
	thumbnail: string;
	video_text: string;
	video_url: string;
	vod: string;
    genre: CategoryType;
	category: string;
	summary_title: string;
	summary_text: string;
	author_1: string;
	author_organiation: string;
	author_2: string;
	author_3: string;
	director_1: string;
	director_2: string;
	director_3: string;
	producer_1: string;
	producer_2: string;
	producer_3: string;
	producer_4: string;
	producer_5: string;
	producer_6: string;
	producer_7: string;
	producer_8: string;
	producer_9: string;
	screenwriter_1: string;
	screenwriter_2: string;
	staff: string;
	production_1: string;
	production_2: string;
	cast_1: string;
	cast_role_1: string;
	cast_2: string;
	cast_role_2: string;
	cast_3: string;
	cast_role_3: string;
	cast_4: string;
	cast_role_4: string;
	cast_5: string;
	cast_role_5: string;
	cast_6: string;
	cast_role_6: string;
	cast_7: string;
	cast_role_7: string;
	cast_8: string;
	cast_role_8: string;
	cast_9: string;
	cast_role_9: string;
	cast_10: string;
	cast_role_10: string;
	cast_11: string;
	cast_role_11: string;
	cast_12: string;
	cast_role_12: string;
	cast_13: string;
	cast_role_13: string;
	cast_14: string;
	cast_role_14: string;
	cast_15: string;
	cast_role_15: string;
	sns_1: string;
	sns_2: string;
	sns_3: string;
	duration_time: string;
	series_number: string;
	publisher: string;
	other_publisher: string;
	website: string;
	original_work: string;
	original_work_organization: string;
	label: string;
	duration_period: string;
	volume: string;
	content_genre: string;
	content_subgenre: string;
	distributor: string;
	distributor_overseas: string;
	copyright: string;
	production_year: string;
	thumbnail_text: string;
	thumbnail_link: string;
	summary_reference: string;
	summary_link: string;
};

export type ArticleItem = {
	id: string;
	genreType: CategoryType;
	tagType: 'root' | 'series' | 'episode';
	pathName: string;
	parentId?: string;
	title: string;
	titleMeta?: string;
	descriptionMeta?: string;
	networkId: string;
	seasonId?: string;
	thumbnail?: {
		url: string;
		text: string;
		link: string[];
	};
	categoryId: string;
	summary: {
		title: string;
		text: string;
		reference: string;
		link: string[];
	};
	authorOrganiation?: string;
	staff?: string;
	otherProduction?: string;
	sns?: string[];
	durationTime?: string;
	seriesNumber?: string;
	publisher?: string;
	otherPublisher?: string;
	website?: string;
	originalWorkOrganization?: string;
	label?: string;
	durationPeriod?: string;
	volume?: string;
	content: { genre: string; subgenre: string };
	distributor?: string;
	distributorOverseas?: string;
	copyright?: string;
	productionYear?: string;
	video: { text: string; url: string };
	sort: number;
	['genreType#tagType#sort']: string;
	['pathName#sort']: string;
};

export type ArticleVod = {
	articleId: string;
	vodId: string;
};

export type ArticleCast = {
	articleId: string;
	personId: string;
	roleName: string;
};

export type ArticlePerson = {
	articleId: string;
	personId: string;
};

export type ArticleProduction = {
	articleId: string;
	productionId: string;
};
