import { checkId, checkNumberOrEmpty, checkNumbersCommaSplitOrEmpty } from '@admin/_lib/utils/csv-data-regx';

export const objectMappers = [
	{ name: 'id', index: 0, check: checkId },
	{ name: 'broadcast_day', index: 1 },
	{ name: 'weekday', index: 2 },
	{ name: 'title_path', index: 3 },
	{ name: 'series_path', index: 4 },
	{ name: 'episode_path', index: 5 },
	{ name: 'program_title', index: 6 },
	{ name: 'primary_program', index: 7 },
	{ name: 'title_meta', index: 8 },
	{ name: 'description_meta', index: 9 },
	{ name: 'network_1', index: 10, check: checkId },
	{ name: 'datetime_1', index: 11 },
	{ name: 'network_2', index: 12 },
	{ name: 'datetime_2', index: 13 },
	{ name: 'season', index: 14 },
	{ name: 'thumbnail', index: 15 },
	{ name: 'cta1_microcopy', index: 16 },
	{ name: 'cta1_botumn_text', index: 17 },
	{ name: 'cta1_url', index: 18 },
	{ name: 'cta2_botumn_text', index: 19 },
	{ name: 'cta2_url', index: 20 },
	{ name: 'video_text', index: 21 },
	{ name: 'video_url', index: 22 },
	{ name: 'vod_info', index: 23 },
	{ name: 'vod', index: 24, check: checkNumbersCommaSplitOrEmpty },
	{ name: 'genre', index: 25 },
	{ name: 'category', index: 26, check: checkId },
	{ name: 'summary_title', index: 27 },
	{ name: 'summary_text', index: 28 },
	{ name: 'comment', index: 29 },
	{ name: 'author_1', index: 30, check: checkNumberOrEmpty },
	{ name: 'author_2', index: 31, check: checkNumberOrEmpty },
	{ name: 'author_3', index: 32, check: checkNumberOrEmpty },
	{ name: 'author_organiation', index: 33 },
	{ name: 'director_1', index: 34, check: checkNumberOrEmpty },
	{ name: 'director_2', index: 35, check: checkNumberOrEmpty },
	{ name: 'director_3', index: 36, check: checkNumberOrEmpty },
	{ name: 'producer_1', index: 37, check: checkNumberOrEmpty },
	{ name: 'producer_2', index: 38, check: checkNumberOrEmpty },
	{ name: 'producer_3', index: 39, check: checkNumberOrEmpty },
	{ name: 'producer_4', index: 40, check: checkNumberOrEmpty },
	{ name: 'producer_5', index: 41, check: checkNumberOrEmpty },
	{ name: 'producer_6', index: 42, check: checkNumberOrEmpty },
	{ name: 'producer_7', index: 43, check: checkNumberOrEmpty },
	{ name: 'producer_8', index: 44, check: checkNumberOrEmpty },
	{ name: 'producer_9', index: 45, check: checkNumberOrEmpty },
	{ name: 'screenwriter_1', index: 46, check: checkNumberOrEmpty },
	{ name: 'screenwriter_2', index: 47, check: checkNumberOrEmpty },
	{ name: 'staff', index: 48 },
	{ name: 'production_1', index: 49, check: checkNumbersCommaSplitOrEmpty },
	{ name: 'production_2', index: 50 },
	{ name: 'cast_1', index: 51, check: checkNumberOrEmpty },
	{ name: 'cast_role_1', index: 52 },
	{ name: 'cast_2', index: 53, check: checkNumberOrEmpty },
	{ name: 'cast_role_2', index: 54 },
	{ name: 'cast_3', index: 55, check: checkNumberOrEmpty },
	{ name: 'cast_role_3', index: 56 },
	{ name: 'cast_4', index: 57, check: checkNumberOrEmpty },
	{ name: 'cast_role_4', index: 58 },
	{ name: 'cast_5', index: 59, check: checkNumberOrEmpty },
	{ name: 'cast_role_5', index: 60 },
	{ name: 'cast_6', index: 61, check: checkNumberOrEmpty },
	{ name: 'cast_role_6', index: 62 },
	{ name: 'cast_7', index: 63, check: checkNumberOrEmpty },
	{ name: 'cast_role_7', index: 64 },
	{ name: 'cast_8', index: 65, check: checkNumberOrEmpty },
	{ name: 'cast_role_8', index: 66 },
	{ name: 'cast_9', index: 67, check: checkNumberOrEmpty },
	{ name: 'cast_role_9', index: 68 },
	{ name: 'cast_10', index: 69, check: checkNumberOrEmpty },
	{ name: 'cast_role_10', index: 70 },
	{ name: 'cast_11', index: 71, check: checkNumberOrEmpty },
	{ name: 'cast_role_11', index: 72 },
	{ name: 'cast_12', index: 73, check: checkNumberOrEmpty },
	{ name: 'cast_role_12', index: 74 },
	{ name: 'cast_13', index: 75, check: checkNumberOrEmpty },
	{ name: 'cast_role_13', index: 76 },
	{ name: 'cast_14', index: 77, check: checkNumberOrEmpty },
	{ name: 'cast_role_14', index: 78 },
	{ name: 'cast_15', index: 79, check: checkNumberOrEmpty },
	{ name: 'cast_role_15', index: 80 },
	{ name: 'sns_1', index: 81 },
	{ name: 'sns_2', index: 82 },
	{ name: 'sns_3', index: 83 },
	{ name: 'broadcast_slot', index: 84 },
	{ name: 'duration_time', index: 85 },
	{ name: 'series_number', index: 86, check: checkNumberOrEmpty },
	{ name: 'publisher', index: 87 },
	{ name: 'other_publisher', index: 88 },
	{ name: 'website', index: 89 },
	{ name: 'original_work', index: 90, check: checkNumbersCommaSplitOrEmpty },
	{ name: 'original_work_organization', index: 91 },
	{ name: 'label', index: 92 },
	{ name: 'duration_period', index: 93 },
	{ name: 'volume', index: 94, check: checkNumberOrEmpty },
	{ name: 'content_genre', index: 95 },
	{ name: 'content_subgenre', index: 96 },
	{ name: 'distributor', index: 97 },
	{ name: 'distributor_overseas', index: 98 },
	{ name: 'copyright', index: 99 },
	{ name: 'production_year', index: 100 },
	{ name: 'thumbnail_text', index: 101 },
	{ name: 'thumbnail_link', index: 102 },
	{ name: 'summary_reference', index: 103 },
	{ name: 'summary_link', index: 104 },
];
